name: Email Notification on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Action Notification"
          to: recipient@example.com
          from: sender@example.com
          content_type: text/html
          body: |
            <h1>GitHub Action Notification</h1>
            <p>Your workflow has completed successfully.</p>
